import React, { useState } from 'react';
import { Sun } from 'lucide-react';

export const SpaceWeatherAndMagnetosphere: React.FC = () => {
  const [activeWeatherStep, setActiveWeatherStep] = useState<number>(1);
  const [selectedMagWorld, setSelectedMagWorld] = useState<'jupiter' | 'earth' | 'saturn' | 'mercury'>('jupiter');

  const weatherSteps = [
    { step: 1, title: '1. Solar Flares & CMEs', desc: 'The Sun erupts with magnetic reconnection flares and Coronal Mass Ejections blasting billions of tons of magnetized plasma at 2,000 km/s.' },
    { step: 2, title: '2. Supersonic Solar Wind', desc: 'Streams of high-energy protons and electrons sweep across interplanetary space toward the planets.' },
    { step: 3, title: '3. Bow Shock & Magnetosphere', desc: 'A planet internal magnetic field deflects charged solar wind particles like a cosmic shield.' },
    { step: 4, title: '4. Auroras & Space Weather', desc: 'Trapped particles channel along magnetic field lines into polar atmospheres, producing glowing auroras.' }
  ];

  return (
    <section id="space-weather-and-magnetosphere" className="glass-panel p-6 sm:p-10 rounded-3xl border border-slate-200 dark:border-cyan-500/20 bg-white/90 dark:bg-slate-900/80 space-y-12 shadow-xl">
      
      {/* 🌡️ 1. SPACE WEATHER PIPELINE */}
      <div className="space-y-6">
        <div className="border-b border-slate-200 dark:border-white/10 pb-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-mono font-bold bg-amber-500/10 dark:bg-amber-500/20 border border-amber-500/30 text-amber-800 dark:text-amber-300">
            <Sun className="w-4 h-4 text-amber-600 dark:text-amber-400" />
            <span>SOLAR-TERRESTRIAL PHYSICS</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-display font-black text-slate-900 dark:text-white mt-1">
            SPACE WEATHER — FROM SUN TO PLANETS
          </h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono text-xs">
          {weatherSteps.map((st) => (
            <div
              key={st.step}
              onClick={() => setActiveWeatherStep(st.step)}
              className={`glass-panel p-5 rounded-2xl border cursor-pointer transition-all ${
                activeWeatherStep === st.step
                  ? 'border-amber-500 bg-amber-500/10 shadow-md font-bold'
                  : 'border-slate-200 dark:border-white/10 bg-white/80 dark:bg-slate-950/80'
              }`}
            >
              <h3 className="text-base font-display font-bold text-slate-900 dark:text-white">{st.title}</h3>
              <p className="font-sans text-xs text-slate-600 dark:text-slate-300 mt-2 leading-relaxed">{st.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* 🧲 2. MAGNETOSPHERE SIZE COMPARISON */}
      <div className="glass-panel p-6 sm:p-8 rounded-2xl border border-cyan-500/40 bg-slate-950 text-white space-y-6 shadow-2xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4">
          <div>
            <span className="text-xs font-mono text-cyan-400 font-bold uppercase block">
              COSMIC MAGNETIC SHIELDS
            </span>
            <h3 className="text-2xl font-display font-black text-white">
              MAGNETOSPHERE COMPARISON
            </h3>
          </div>

          <div className="flex items-center gap-2 font-mono text-xs">
            {(['jupiter', 'earth', 'saturn', 'mercury'] as const).map((mw) => (
              <button
                key={mw}
                onClick={() => setSelectedMagWorld(mw)}
                className={`px-3 py-1.5 rounded-xl uppercase font-bold border transition-all ${
                  selectedMagWorld === mw
                    ? 'bg-cyan-500 text-slate-950 border-cyan-400'
                    : 'bg-white/10 text-slate-300 border-white/10'
                }`}
              >
                {mw}
              </button>
            ))}
          </div>
        </div>

        <div className="bg-white/5 p-5 rounded-xl border border-white/10 font-mono text-xs space-y-2">
          {selectedMagWorld === 'jupiter' && (
            <p className="font-sans text-slate-300 text-sm">
              <strong>JUPITER MAGNETOSPHERE:</strong> The largest contiguous structure in the Solar System after the Sun heliosphere! Extends 3 to 7 million km sunward and stretches 700 million km back to Saturn orbit. If visible in Earth night sky, it would appear <strong>2x larger than the Full Moon</strong> despite being hundreds of millions of km away!
            </p>
          )}
          {selectedMagWorld === 'earth' && (
            <p className="font-sans text-slate-300 text-sm">
              <strong>EARTH MAGNETOSPHERE:</strong> Generated by molten liquid iron rotation in Earth outer core. Extends ~65,000 km sunward and deflects lethal cosmic radiation and solar wind plasma, protecting our atmosphere and surface life.
            </p>
          )}
          {selectedMagWorld === 'saturn' && (
            <p className="font-sans text-slate-300 text-sm">
              <strong>SATURN MAGNETOSPHERE:</strong> Symmetrical dipolar field perfectly aligned with Saturn rotation axis. Fueled by water ice grains erupted from Enceladus geysers.
            </p>
          )}
          {selectedMagWorld === 'mercury' && (
            <p className="font-sans text-slate-300 text-sm">
              <strong>MERCURY MAGNETOSPHERE:</strong> Surprisingly possesses a global magnetic dipole (~1% of Earth strength) generated by its oversized partially molten metallic core.
            </p>
          )}
        </div>
      </div>

    </section>
  );
};
