import type { Moon } from '../types';

export const moonsData: Moon[] = [
  {
    id: 'moon-luna',
    name: 'Moon (Luna)',
    parentPlanet: 'Earth',
    diameter: '3,474.8 km',
    orbitalPeriod: '27.32 days',
    distanceFromParent: '384,400 km',
    description: 'Earth’s only natural satellite. Synchronously locked with Earth, showing the same side always. Influences ocean tides and stabilizes Earth’s axial tilt.',
    image: 'https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Contains water ice in shadowed craters at the lunar poles; host to humanity’s 6 Apollo landings.',
    sources: [{ name: 'NASA', url: 'https://science.nasa.gov/moon/' }, { name: 'ISRO', url: 'https://www.isro.gov.in/Chandrayaan3_Details.html' }]
  },
  {
    id: 'europa',
    name: 'Europa',
    parentPlanet: 'Jupiter',
    diameter: '3,121.6 km',
    orbitalPeriod: '3.55 days',
    distanceFromParent: '670,900 km',
    description: 'Smooth icy world covering a global subsurface liquid ocean holding twice the water of all Earth oceans combined.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Plumes of water vapor erupting through liquid ocean cracks make Europa a primary astrobiology target.',
    sources: [{ name: 'NASA', url: 'https://science.nasa.gov/jupiter/moons/europa/' }]
  },
  {
    id: 'titan',
    name: 'Titan',
    parentPlanet: 'Saturn',
    diameter: '5,149.5 km',
    orbitalPeriod: '15.95 days',
    distanceFromParent: '1.22 million km',
    description: 'Saturn’s largest moon and second-largest moon in the solar system. Has dense nitrogen atmosphere and liquid hydrocarbon lakes.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Only planetary moon with dense atmosphere and weather cycle based on liquid methane instead of water.',
    sources: [{ name: 'ESA', url: 'https://www.esa.int/' }, { name: 'NASA', url: 'https://science.nasa.gov/saturn/moons/titan/' }]
  },
  {
    id: 'io',
    name: 'Io',
    parentPlanet: 'Jupiter',
    diameter: '3,643.2 km',
    orbitalPeriod: '1.77 days',
    distanceFromParent: '421,700 km',
    description: 'The most volcanically active body in the Solar System with over 400 active volcanoes spewing sulfur lakes.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Tidal friction from Jupiter and neighboring moons generates immense internal geothermal heat.',
    sources: [{ name: 'NASA', url: 'https://science.nasa.gov/jupiter/moons/io/' }]
  },
  {
    id: 'ganymede',
    name: 'Ganymede',
    parentPlanet: 'Jupiter',
    diameter: '5,268.2 km',
    orbitalPeriod: '7.15 days',
    distanceFromParent: '1.07 million km',
    description: 'Largest moon in the Solar System (larger than Mercury and Pluto).',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Only moon known to possess a intrinsic magnetosphere generated by a liquid iron core.',
    sources: [{ name: 'ESA', url: 'https://www.esa.int/' }]
  },
  {
    id: 'enceladus',
    name: 'Enceladus',
    parentPlanet: 'Saturn',
    diameter: '504.2 km',
    orbitalPeriod: '1.37 days',
    distanceFromParent: '238,000 km',
    description: 'Bright icy moon of Saturn with active cryovolcanoes in its south polar "tiger stripe" fractures.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Cassini detected hydrothermal activity, phosphorus, and organic matter in Enceladus plume ice grains.',
    sources: [{ name: 'NASA', url: 'https://www.nasa.gov/cassini' }]
  },
  {
    id: 'triton',
    name: 'Triton',
    parentPlanet: 'Neptune',
    diameter: '2,706.8 km',
    orbitalPeriod: '5.88 days (Retrograde)',
    distanceFromParent: '354,800 km',
    description: 'Neptune’s largest moon, believed to be a captured Kuiper Belt Object orbiting backwards.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Active geysers erupting liquid nitrogen gas and dust 8 kilometers above the surface.',
    sources: [{ name: 'NASA', url: 'https://science.nasa.gov/neptune/moons/triton/' }]
  },
  {
    id: 'phobos',
    name: 'Phobos',
    parentPlanet: 'Mars',
    diameter: '22.5 km',
    orbitalPeriod: '7 hours 39 minutes',
    distanceFromParent: '9,376 km',
    description: 'Small, potato-shaped moon orbiting Mars just 6,000 km above the surface. Gradually spiraling inward towards Mars.',
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
    keyDiscovery: 'Orbits Mars 3 times per Martian day; predicted to break apart into a Martian ring in 30-50 million years.',
    sources: [{ name: 'NASA', url: 'https://science.nasa.gov/mars/moons/phobos/' }]
  }
];
